- name: copy module test
  hosts: servers
  tasks:
  - copy: dest=/home/ansible/hello content=world
  - file: path=/home/ansible/test state=directory

# - name: Create a directory if it does not exist
#   hosts: servers
#   ansible.builtin.file:
#     path: /home/ansible/test
#     state: directory
#     mode: '0755'