- hosts: servers
  become: true
  tasks:
    - name: copy stuff
      copy: dest=/home/ansible/hello content=world

    - name: create stuff
      file: path=/home/ansible/test state=directory

    # - name: create xcloud folder
    #   file: path=/home/ansible/xcloud state=directory

    - name: manage mysql client
      apt:
        update_cache: yes
        name: mysql-client-core-8.0
        state: present

    - name: manage fping
      apt:
        update_cache: yes
        name: fping
        state: present

    - name: manage curl
      apt:
        update_cache: yes
        name: curl
        state: absent

# - name: Create a directory if it does not exist
#   hosts: servers
#   ansible.builtin.file:
#     path: /home/ansible/test
#     state: directory
#     mode: '0755'