tasks:
- name: copy module test
  hosts: servers
  become: true
  - copy: dest=/home/anisble/hello content=world

- name: Create a directory if it does not exist
  hosts: servers
  - ansible.builtin.file:
    path: /home/ansible/test
    state: directory
    mode: '0755'